### ISSUE TITLE
TypeError: The added layer must be an instance of class Layer

### ISSUE THREAD

**Issue by atracordis** [philipperemy/keras-tcn#101]
In a fresh Google Colab Notebook, I executed the contents of this sample task :
https://github.com/philipperemy/keras-tcn/blob/master/tasks/sequential.py
The error appeared at model.add(TCN(nb_filters=64, kernel_size=6, dilations=[1, 2, 4, 8, 16, 32, 64]))
Are TCN layers not considered layers by Tensorflow?

**Comment by atracordis** [comment]
Circumvented the error by simply copying and executing the contents of the tcn.py class (link : https://github.com/philipperemy/keras-tcn/blob/master/tcn/tcn.py ) into my Notebook instead of importing it from the installed library

**Comment by philipperemy** [comment]
@atracordis thanks for reporting. Sorry I forgot to push to PyPI the latest version of master. It should work now: 2.9.0.
