### ISSUE TITLE
TCN layer config does not account for layer norm

### ISSUE THREAD

**Issue by adamconkey** [philipperemy/keras-tcn#104]
The new Layer inheritance for the TCN layer does not account for the new option `use_layer_norm` in the configuration in [`get_config`](https://github.com/philipperemy/keras-tcn/blob/1c81970433fb0bd2ea4444edd0ff87b2c5d09464/tcn/tcn.py#L281). This causes deserialization problems as the number of weights in the layer do not match with what was present when the model was serialized. For instance, something like
```
model.save_weights("my_model.h5")
model = tf.keras.models.load_model("my_model.h5", custom_objects={'TCN': TCN})
```
gave me this error:
```
ValueError: Layer #2 (named "tcn" in the current model) was found to correspond to layer tcn in the save file. However the new layer tcn expects 24 weights, but the saved weights have 40 elements.
```
The fix is simple, just add `config['use_layer_norm'] = self.use_layer_norm` in the `get_config` function of the TCN layer. I have submitted PR #105 to fix this.

**Comment by philipperemy** [comment]
Merged in 2.9.1 

Version: https://github.com/philipperemy/keras-tcn/commit/3a7b8d7e2f5e4a5c5c95f5281b67400047d9722e
Commit: https://github.com/philipperemy/keras-tcn/commit/6fec40ef7465aebe95ffe612e107d97df72121e4
