### ISSUE TITLE
sequence to sequence attention

### ISSUE THREAD

**Issue by slateralus** [philipperemy/keras-tcn#107]
Hi @philipperemy ,
I am working on seq2seq problem and I want to try following architecture:

Tcn Block
Seq2seq attention
Tcn Block
etc

I am looking for implementation of sequence to sequence attention using keras?
Do you aware about something similar ?

Thanks

**Comment by philipperemy** [comment]
@slateralus well any architecture you can find on the internet with LSTM -> Attention -> LSTM will work well with TCN. TCN are LSTM are inter-changeable.
