### ISSUE TITLE
function comments

### ISSUE THREAD

**Issue by nbertagnolli** [philipperemy/keras-tcn#11]
I really like this implementation : ).  I pulled this down and took the time to understand it.  I added a bunch of comments to the functions, do you have any interest in me opening a pull request?

**Comment by issa-s-ayoub** [comment]
Yea adding the comments will be very helpful!!

**Comment by philipperemy** [comment]
@nbertagnolli yeah sure go ahead!

**Comment by philipperemy** [comment]
Merged https://github.com/philipperemy/keras-tcn/commit/7e48d5c722f39138f1766a25403f96ea72f4bd5a

Thanks again
