### ISSUE TITLE
Question about the TCN parameters

### ISSUE THREAD

**Issue by zibozzb** [philipperemy/keras-tcn#112]
Hi Philipperemy,
Thanks for your code.
I have some questions about the TCN arguments.

My testing code:
A1 = Input(batch_shape=(500, 1000, 1), name='A1')
A2 = TCN(nb_filters=64, kernel_size=2, nb_stacks=1, dilations=(1, 2))(A1) 
A3 = Dense(1, activation='linear', name='A3')(A2)
and I generated the architecture figure posted in the end.

**Questions:**
1. I used dilations=(1, 2), which means I should get a TCN with two dilation causal conv layers. Why does the figure contain 6 conv layers?
2. As depicted from the figure, it seems like 2 dilations represent two blocks in the figure (left side, right side).  Why does each block have 2 conv layers?

THANKS!!
![default_tcn_architecture_2](https://user-images.githubusercontent.com/22671851/72048834-a9de9100-328b-11ea-9eeb-54a24aa66c1b.png)

**Comment by psomers3** [comment]
You'll find your answers in the original paper this repository was based on. The authors decided to use 2 layers in each residual block and there exists an identity convolution to help with matching dimensions.

[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=10&ved=2ahUKEwjsy-7NwpnnAhXOiVwKHVegALcQFjAJegQIBxAB&url=https%3A%2F%2Farxiv.org%2Fpdf%2F1811.10166&usg=AOvVaw37QMZPWyTGpEo0i5Xw1jd7](url)

**Comment by philipperemy** [comment]
@zibozzb by the way which version do you use and how did you generate this cool graph? Did you use `plot_model`?

**Comment by zibozzb** [comment]
Sorry for getting back late. YES, it is plot_model. I used 2.8.3 for TCN.

**Comment by philipperemy** [comment]
I'll close this issue for now. If you have any other questions please make a new issue :)
