### ISSUE TITLE
Resource exhausted

### ISSUE THREAD

**Issue by thomashirtz** [philipperemy/keras-tcn#117]
Hello,
I would like to know if I made  a mistake using your library
I want to do a TCN that does from an array of ~43000 to an output of ~100 to an hidden layers, then several outputs (regression problem. For this example I wanted to use only one output to see if everything was ok). However I get Ressource exhausted, But I feel like it is weird since the number of parameters should decrease exponentially with the layers, and therefore not be too substantial

My network is:
```
from tensorflow.keras import Input, Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tcn import TCN

model = Sequential()
model.add(TCN(nb_filters=100, dilations=dilations,nb_stacks=nb_stacks, return_sequences=False))
model.add(Dense(100))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
```

kernel_size:  2
For the dilations I tried several things by either adding more dilations or more stacks
stacks = 4 and dilations = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]
or
stacks = 1 and dilations = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]

error:
```
(0) Resource exhausted: OOM when allocating tensor with shape[1,45248,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node sequential/tcn/residual_block_11_1/conv1D_0/Pad}}]]
```

Do you see something weird ? 
Or Am I just pushing the numbers too much ?
It bothers me because it was working quite well with pytorch, but for some reason I need to migrate my project to TF/Keras

Thanks !

**Comment by psomers3** [comment]
That just seems like a huge network, so on a local machine that doesn't surprise me. Were you using the GPU with pytorch? The number of parameters is not what is allocated on the GPU. The math operations are and since the structure is full of 1:1 convolutions, I imagine the operations aren't any smaller toward the end of the network.

**Comment by thomashirtz** [comment]
I must admit that my computer is not really powerful, but I trained some time ago a VGG which is quite bigger and include more than 100 millions parameters. 
I thought that my network, when using as an input an array of 50000 (one channel) has :
50000+25000+12500+7500+...+200 (TCN from 50000 to 100)+100*100 (Hidden layer 1)+100(Hidden layer 2) Parameters. Which is ~less than 100000 parameters
Am I missing something in my calculus ? (now I am even more curious) 
I know you told me the math must have been more complex but it makes me perplex

Can you precise the 1:1 convolution that you just mentioned so I can do some more research

I was using GPU with pytorch
However I was doing a TCN reduction from 50000 to 100 output and then using a dense layer, which seems to be different from what I am doing with this network (from 50000 to 1 but with 100 units) I am not sure if you understand my point, and I can't see how to do similar things with this library

**Comment by philipperemy** [comment]
@thomashirtz can you print the model summary?

```
model.summary()
```

It will be helpful to see how many parameters you have inside your model.

**Comment by philipperemy** [comment]
I'll close this issue. It seems to be related to a very very huge model that does not fit on the GPU: `stacks = 1 and dilations = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]`.
