### ISSUE TITLE
Implement nb_filters=[1,2,4,8]

### ISSUE THREAD

**Issue by thomashirtz** [philipperemy/keras-tcn#118]
Would it be possible to implement a feature to input a list of nb_filters ?
e.g. if I want a network with dilations = [1,2,4,8] and nb_filters=[1,2,4,8]
(I don't feel like I need to have high number of filters in the beginning, but rather at the end)

**Comment by philipperemy** [comment]
Yes it sounds def do-able.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/pull/135 @thomashirtz I created a PR.
If you want to give me your feedback, feel free to do it. Thanks!

**Comment by thomashirtz** [comment]
Woa, nice!
I am not working on TCN these days. I will certainly let you know in a if few weeks when I'll try :)

**Comment by philipperemy** [comment]
@thomashirtz sure no problem!

**Comment by philipperemy** [comment]
Merged https://github.com/philipperemy/keras-tcn/commit/afdb50a9ed622326151187f0f0b84b7896cfcd72
