### ISSUE TITLE
model.summary without detail of each layer in tcn 

### ISSUE THREAD

**Issue by Hessen525** [philipperemy/keras-tcn#119]
Hi, philipperemy 
Thanks for you work! Model.summary without detail of each layer in tcn block. As we know tcn include dilated convolutions and skip connect and so on, but we can not see the detail, likes output shape, parameter for each layer inside tcn. Do you know any ways to show it ? 

Any reply/advice will be much appreciated!

**Comment by Hessen525** [comment]
@https://github.com/philipperemy/keras-tcn/issues/108, someone have asked for same question.

**Comment by philipperemy** [comment]
@Hessen525 yes that would be very useful. But because TCN became a keras.layer itself, model summary does not allow such a level of details.. I'll be happy to implement something if someone can somehow find a workaround.

**Comment by philipperemy** [comment]
@psomers3 amazing work. @Hessen525 this was released to master. Thanks again!
