### ISSUE TITLE
The training of TCN is much slower than FCN. 

### ISSUE THREAD

**Issue by Hessen525** [philipperemy/keras-tcn#123]
Hi, @philipperemy 
Thanks for your code, but I have a question as following:
Is it normal that tcn with 80,0000 parameters  is much slower than FCN with 30,000,000 parameters?

**Comment by philipperemy** [comment]
What is the unit W? @Hessen525

**Comment by Hessen525** [comment]
> What is the unit W? @Hessen525

Thanks for your quick reply, 1W= 10,000 So 80W=800,000.

**Comment by philipperemy** [comment]
@Hessen525  80,0000 means 800K ?

**Comment by Hessen525** [comment]
> @Hessen525 80,0000 means 800K ?
Do not worry about it, In another word,  Is it normal that tcn with 80,0000 parameters is much slower than FCN with 30,000,000 parameters for training time?

**Comment by philipperemy** [comment]
@Hessen525 FC layers are very fast to compute. It's just a matrix multiplication. TCN is a stack of residual blocks with many causal convolutions. It's definitely normal that it takes more time.
