### ISSUE TITLE
Provide the TCN model with additional status information for each sample 

### ISSUE THREAD

**Issue by annebierhoff** [philipperemy/keras-tcn#127]
Hi Philipperemy,
Thanks for your effort.

I want to map a storage as a TCN model, which receives as input the removal from the storage and addition to the storage for t=0 to t=n and returns as output the storage contents.
For this purpose it is necessary to tell the TCN model the initial storage value at t=0 of each sample. 

What is the best way to provide the TCN network with this isolated information?

**Comment by philipperemy** [comment]
Thanks!
What do you mean by storage?

**Comment by annebierhoff** [comment]
> Thanks!
> What do you mean by storage?

A storage device for storing electricity

**Comment by philipperemy** [comment]
@annebierhoff have a look at this tutorial: https://machinelearningmastery.com/time-series-prediction-lstm-recurrent-neural-networks-python-keras/
You can replace `LSTM` by `TCN`.
