### ISSUE TITLE
How to train own data by TCN?

### ISSUE THREAD

**Issue by Yangandtom** [philipperemy/keras-tcn#129]
I build the TCN model is as follows：
model = Sequential()
model.add(TCN(50,return_sequences=False, input_shape=(nb_features,12))) 
model.add(Dense(100, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_class,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])
model.summary()
However, 
TypeError: The added layer must be an instance of class Layer. Found: <tcn.TCN object at 0x000001A8B62CA208>

**Comment by psomers3** [comment]
make sure you import the keras layers from tensor flow and not directly from keras.

```python
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout
```

**Comment by Yangandtom** [comment]
> make sure you import the keras layers from tensor flow and not directly from keras.
> 
> ```python
> from tensorflow.keras import Sequential
> from tensorflow.keras.layers import Dense, Dropout
> ```

Excellent! It solved my problem perfectly.Thank you!
