### ISSUE TITLE
Video processing recommendations

### ISSUE THREAD

**Issue by miaoweiwei** [philipperemy/keras-tcn#130]
I read the source code and found that the project is currently unable to process video, it is recommended to increase the function of processing video

**Comment by philipperemy** [comment]
@miaoweiwei I uploaded an example to demonstrate how to do video processing with a RNN network: https://github.com/philipperemy/keras-tcn/blob/master/tasks/video_classification.py

It's a simple one. If you have time, it'd be great if you can make a pull request by changing this dummy data loader to something that makes more sense such as:

- https://www.crcv.ucf.edu/data/UCF101.php

Useful links:
- https://www.pyimagesearch.com/2019/07/15/video-classification-with-keras-and-deep-learning/
- https://github.com/sujiongming/UCF-101_video_classification
