### ISSUE TITLE
Which paper is implemented ? TCN or Wavenet

### ISSUE THREAD

**Issue by hugoych** [philipperemy/keras-tcn#131]
Hi there,
First of all, thanks for the time you take for maintaining this library, it's really appreciated ! 

I want to work with TCN from https://arxiv.org/pdf/1803.01271.pdf . 
By having a fist look at the code it seems you are indeed implementing this paper idea of a CNN for time series, by stacking two dilated 1D convolution with a ReLu activation in a Residual block.

However when looking closer there also seems to be some features from WaveNet architecture https://arxiv.org/pdf/1609.03499.pdf. 
Indeed you implement skip connections in between the convolutions output and the residual sum. This is close to what WaveNet is doing. However they do that after a gated convolution instead of two stacked convolutions like in the code. 

So my question is what paper are you implementing here TCN or WaveNet ? 

If we remove skip connections, use only one stack of residual blocks and change the activation to be ReLu after residual sum, we indeed fall back on the TCN original paper architecture. However in the part about result reproductions you do use skip connections. 

Thanks in advance for your answers @philipperemy !

**Comment by philipperemy** [comment]
Hello Hugo,
Thank you for the feedback, much appreciated!
This implementation refers to https://arxiv.org/pdf/1803.01271.pdf.
And yes you are correct, `use_skip_connections=True` is enabled by default and is used in the reproducibility of the results which is not strictly rigorous.
By default, it should be set to `False`.
`use only one stack of residual blocks and change the activation to be ReLu after residual sum` => I don't remember in details how it's done but if you see any changes that differs from https://arxiv.org/pdf/1803.01271.pdf, feel free to make a small PR :)

**Comment by hugoych** [comment]
Thanks for your quick answer !
I'll do that then :).
Another question I have is regarding `self.main_conv1D` in `tcn.TCN`. Why do you do this first convolution prior to entering your residual blocks ? Is there some size issue I missed somewhere ?

Finally for the residual sum you apply a 1D convolution of kernel_size 1 if the block is not last ? Is there a reason for that ? In the original paper a 1D convolution is applied only if the input number of features is different from the output number of features.

**Comment by philipperemy** [comment]
@hugoych from my memory, the first main Conv1D is mentioned somewhere in the paper but I can't recall exactly where.

You can also have a look at this repo: https://github.com/locuslab/TCN/

This is the authors' implementation (PyTorch). I've never really had the chance to go through it thoroughly. That'd be great if you could compare the two versions (Keras and PyTorch) and make sure the arch are the same.

![image](https://user-images.githubusercontent.com/4516927/79818322-7d75fd00-83c2-11ea-8ed6-836809fc2a4c.png)

![image](https://user-images.githubusercontent.com/4516927/79818333-823ab100-83c2-11ea-8de2-a5ba35513f12.png)

Now that you mention it, there's the word optional in the second one. So there might be something to do there too.

Thanks a lot for all those useful insights :)

**Comment by hugoych** [comment]
From the snippet they mention the 1D convolution from the residual block in my understanding. I looked at the code (https://github.com/locuslab/TCN/blob/2221de3323032faef7bde744b0e211bd274cb2d0/TCN/tcn.py#L15-L45), There is no sign of a first convolution with kernel size 1. Moreover the 1x1 conv in the residual block is only applied if `n_inputs != n_outputs`.
I'll make a small PR when I have time :)

**Comment by philipperemy** [comment]
@hugoych great! Please find some time :)

**Comment by philipperemy** [comment]
PR related: https://github.com/philipperemy/keras-tcn/pull/133
