### ISSUE TITLE
Multivariate Time Series Classification

### ISSUE THREAD

**Issue by methk** [philipperemy/keras-tcn#134]
Hello, I found [multi_length_sequences.py](https://github.com/philipperemy/keras-tcn/blob/master/tasks/multi_length_sequences.py) very useful and very effective to classify different length time series.

I'd like to ask if is it possible to classify **multivariate time series** (with different lengths) as well. I'm quite new in CNN and, specifically in TCN, so if you have a Python toy example or any hint I'd really appreciate it.

Thank you.

**Comment by slateralus** [comment]
Hi @methk 
Are you are talking about [multi task learning](https://ruder.io/multi-task/index.html#hardparametersharing) ?

Thanks.

**Comment by methk** [comment]
Hi @slateralus, thanks for your reply.
I think my problem is easier than multi task learning. I'd like to classify time series of different lengths as [multi_length_sequences.py](https://github.com/philipperemy/keras-tcn/blob/master/tasks/multi_length_sequences.py) but these time series have a dimension greater than 1.

For example you can think of a multivariate time series as a series of length N where each point in time is an array of 3 elements (e.g. X, Y and Z values of a gyroscope).

**Comment by slateralus** [comment]
Hi @methk 

`Input(batch_shape=(BATCH_SIZE, MAX_TIME_STEPS, EMBEDDING_LENGTH)`
In your case `EMBEDDING_LENGTH = 3`

Thanks.

**Comment by methk** [comment]
Thank you @slateralus, I did a quick test and it seems to work fine. I'll try more specific tests in the next hours and I will close the issue.

Thank you again.
