### ISSUE TITLE
 fully convolution layer

### ISSUE THREAD

**Issue by HouKun-github** [philipperemy/keras-tcn#139]
Why is this version of the one-dimensional fully convolution layer gone? The previous version had a one-dimensional full convolution, at least the original paper used full convolution to ensure that the sequence is not missing, can you explain?

**Comment by philipperemy** [comment]
@HouKun-github hey could it be linked to https://github.com/philipperemy/keras-tcn/pull/133?

**Comment by philipperemy** [comment]
Yes, you are right. The 1-D fully convolutional layer is gone and I think it is because we found that removing it boosted the performance (or did not deteriorate the performance of the model, cf. Occam razor). I agree that we don't match the original paper 100% now because of this change.
