### ISSUE TITLE
How to do with both numeric variables and categorical variables?

### ISSUE THREAD

**Issue by sychen1218** [philipperemy/keras-tcn#147]
Hello, my input data  has both numeric variables and categorical variables? and one of categorical variables has many values, for example 'id', there are more than 1000 values, how to input them to TCN?

Looking forward to your reply, Thanks very much!

**Comment by philipperemy** [comment]
The easiest way is to use one-hot encoding for your categorical variables and concatenate them with the numeric values and feed that as a big tensor to the TCN. But ideally, you would like to condition on those categorical variables. 
You can check this repo it might get you some ideas: https://github.com/philipperemy/cond_rnn.
Re-open this issue if you have more questions!
