### ISSUE TITLE
the model save but dosnt load   - ValueError: Unknown layer: TCN 

### ISSUE THREAD

**Issue by nas2000co** [philipperemy/keras-tcn#155]
thanks ,  it is very fast and has very good Performance 

Unfortunately - i can save Model but  cant load it again ,  always i encounter with below error!!!!!
ValueError: Unknown layer: TCN 

please Help 
for example :  your sample code
![001](https://user-images.githubusercontent.com/67532767/90332896-0c440080-dfd6-11ea-9445-496a2d15ebc5.PNG)

**Comment by philipperemy** [comment]
@nas2000co can you follow the example in https://github.com/philipperemy/keras-tcn/blob/23845be7a35bb8bff6fbd8d3ccb5e7e50c9e4884/tasks/save_reload_sequential_model.py#L1 and tell me?

**Comment by philipperemy** [comment]
I guess you need to give `custom_objects={'TCN': TCN}` when you load the model. Otherwise the layer will be unknown.

**Comment by nas2000co** [comment]
Thanks So much thats worked very well !!!!!!!!!!!!!!!!!!!!

`new_model= tf.keras.models.load_model('model.h5' , custom_objects={'TCN': TCN})`

**Comment by philipperemy** [comment]
Great!!!! I'll close this issue. Happy I could help :)
