### ISSUE TITLE
Load and save different values 

### ISSUE THREAD

**Issue by rjpg** [philipperemy/keras-tcn#160]
using keras model checkpoint : 

`Epoch 00061: val_mse did not improve from 0.02534`

but after load : 

`MSE :  0.03303073
`

I had this problem in my model in keras and it was bad use of lambda functions in keras ...

**Comment by philipperemy** [comment]
@rjpg can you paste a snippet showing that it's not working?

If I refer to this TCN test, it seems to work for this configuration: https://github.com/philipperemy/keras-tcn/blob/master/tasks/save_reload_model.py

**Comment by philipperemy** [comment]
I'll close this issue for inactivity. Please update to the latest TCN and try again. Re-open it if you see something.
