### ISSUE TITLE
the relationship between receptive field and  the input sequence timestep

### ISSUE THREAD

**Issue by Kitaharakasusa** [philipperemy/keras-tcn#162]
I'm confused about this problem, does the receptive field have to be larger than the input timestep? if my  input is [batch_size, 1, 6]
can the TCN work?

**Comment by philipperemy** [comment]
@Kitaharakasusa for a given sequence, the prediction at time t will only see from t-receptive_field to t.
So if you have a sequence of 100 and a receptive field of 20, the TCN will predict 100 values where each one depends on the last 20 values. That means the predict at index 48 for example will only see from 27 up to 47.

**Comment by philipperemy** [comment]
I'll close this question. If it's not clear, please feel free to re-open it. Thank you!
