### ISSUE TITLE
optimizer.apply_gradients doesnt update the weights

### ISSUE THREAD

**Issue by shdeldari** [philipperemy/keras-tcn#164]
Hi,

 I think there might be an issue with updating the weights using optimizer.apply_gradients. When I train the TCN layer using model.fit(), everything is fine and it works well. However, when I try to update the variables using optimizer.apply_gradients, nothing can be learnt. I hope someone can help me with this issue. I appreciate your help. Thanks

```
# Model Definition
inputs = Inputs(h_shape)
xrep = TCN(nb_filters, kernel_size, nb_stacks, dilations, padding,
                    use_skip_connections, dropout_rate, return_sequences=True, activation='relu',
                    kernel_initializer='he_normal', use_batch_norm=True)(inputs)
xrep = Flatten()(xrep)
xrep = Dense(C1)(xrep)
xrep = Activation("relu")(xrep)
xrep = Dense(C2)(xrep)
xrep = BatchNormalization()(xrep)
model = Model(inputs, xrep)

### Update
optimizer = tf.keras.optimizers.Adam(lr=0.01)
gradients = tape.gradient(loss, model.trainable_variables)
optimizer.apply_gradients(zip(gradients, model.trainable_variables))
```
I am using Tensorflow 2.3.0.

**Comment by hayden-lo** [comment]
Hi, I met the same problem as yours, did you solve in the end?
