### ISSUE TITLE
keras-tcn does not seem to use GPU !!

### ISSUE THREAD

**Issue by scstu** [philipperemy/keras-tcn#167]
I'm reporting this Issue while using Colab. After installing Keras-tcn (using !pip install keras-tcn), everything is just working fine. however, every other layer is fast except when integrating tcn into the network, the code went very slow.
btw, I'm using the pro subscription of google colab!.

**Comment by philipperemy** [comment]
@scstu not sure here because it works on GPU when not using collab (at least). So maybe check that you have installed tensorflow-gpu! It works with 2.3.0 (at least).
