### ISSUE TITLE
Keras version

### ISSUE THREAD

**Issue by fsbashiri** [philipperemy/keras-tcn#172]
I am using Keras-tuner (1.0.1) for hyper-parameter tuning, which requires Keras==2.4.3. When I installed Keras-tcn, it automatically installed Keras-tcn 3.1.1 (I assume it's the latest version) and downgraded Keras to keras==2.3.1. The problem is I want to use Keras-tcn and Keras-tuner, which they each require a different version of Keras, and neither work with the version of Keras that is compatible with the other package! 
Does anyone know how I can make Keras-tcn work with keras=2.4.3?

**Comment by philipperemy** [comment]
Um, I'll see that. Ideally, we should not even rely on Keras.

**Comment by philipperemy** [comment]
I'm going to push a new version: 3.1.2. Keras dependency will be removed.

**Comment by philipperemy** [comment]
Version 3.1.2 is out. https://github.com/philipperemy/keras-tcn/commit/f6c3f042ea53a16fd9e0c644837fb7cf4df52e9d

```
pip install keras-tcn --upgrade
``
