### ISSUE TITLE
Does it have a document?

### ISSUE THREAD

**Issue by SharkFin-top** [philipperemy/keras-tcn#176]
Does it have a document?

Thank you!

**Comment by philipperemy** [comment]
@SharkFin-top what do you mean?

**Comment by SharkFin-top** [comment]
> @SharkFin-top what do you mean?
Well...Some more details on how to use it.

**Comment by psomers3** [comment]
[How to use keras-TCN](https://github.com/philipperemy/keras-tcn)

**Comment by philipperemy** [comment]
Yes please refer to the README and the examples.

**Comment by philipperemy** [comment]
Keras TCN can be used the same as any RNN (LSTM, GRU) of Keras.
