### ISSUE TITLE
How do I use the trained model to make predictions about the future?

### ISSUE THREAD

**Issue by SharkFin-top** [philipperemy/keras-tcn#177]
This page TimeSeries Foresting

https://colab.research.google.com/github/ashishpatel26/tcn-keras-Examples/blob/master/TCN_TimeSeries_Approach.ipynb

![image](https://user-images.githubusercontent.com/55095619/103669205-06fe4700-4fb3-11eb-905f-3f7e0c811fbe.png)

This graph shows the model predictions compared to the true values of the training data. How do I use the trained model to make predictions about the future?

For example, the training data is 1962-2019 month data. Use the training data to train the model. What about using the model to predict the data for the next 12 months?

Thank you!

**Comment by psomers3** [comment]
Maybe [this](https://towardsdatascience.com/lstm-time-series-forecasting-predicting-stock-prices-using-an-lstm-model-6223e9644a2f) can help you understand how to use trained models for prediction. An lstm network is used the same as a TCN.

**Comment by SharkFin-top** [comment]
> Maybe [this](https://towardsdatascience.com/lstm-time-series-forecasting-predicting-stock-prices-using-an-lstm-model-6223e9644a2f) can help you understand how to use trained models for prediction. An lstm network is used the same as a TCN.

Thank you so much!

**Comment by philipperemy** [comment]
Thanks guys :) I'll close this issue.
