### ISSUE TITLE
code issue (process_dilations)

### ISSUE THREAD

**Issue by eggpan95** [philipperemy/keras-tcn#18]
Hi, first of all, thanks for your code sharing.
Guessing your intentions, the following expression may be appropriate.

def process_dilations(dilations):
    ...
    else:
        new_dilations = [2 ** i for i in dilations]
 --> new_dilations = [2 ** i for i in range(len(dilations))]

**Comment by philipperemy** [comment]
I think it's correct. 

The idea is that you either give something like:

- case of power of 2: [1, 2, 4, 8, 16, 32, 64]. In that case you just use them as it is.
- range(5). In that case you would do [2 ** i for i in dilations] = [1, 2, 4, 8, 16].
