### ISSUE TITLE
First example gives away the answer by inserting the result into the x_train dataset

### ISSUE THREAD

**Issue by Caedin** [philipperemy/keras-tcn#183]
**Describe the bug**
First example in the documentation gives away the answer by inserting the result into the x_train dataset

I got perfect prediction results with just a few trains on my first run though.

x_train[pos_indices, 0] = 1.0

Removing this line creates a training curve that makes sense. 

Following the example as written: 

![image](https://user-images.githubusercontent.com/8877753/107855237-c0d4a880-6de6-11eb-9ab3-fd1f9803f476.png)

After removing the offending line: 

![image](https://user-images.githubusercontent.com/8877753/107855254-d34ee200-6de6-11eb-9f0d-0faaa1c8b9d4.png)

**Comment by philipperemy** [comment]
Yes I think it was done on purpose to make sure the TCN can go back "in time" to the beginning of the sequence to solve the problem.

**Comment by philipperemy** [comment]
If we remove this line the network will not be able to solve the task.

**Comment by philipperemy** [comment]
I've updated the README to clarify it: https://github.com/philipperemy/keras-tcn/blob/master/README.md

Thanks for reporting :)
