### ISSUE TITLE
Keras-TCN installs tensorflow (cpu version) automatically 

### ISSUE THREAD

**Issue by kiminc66** [philipperemy/keras-tcn#187]
I am trying to install Keras-TCN (ver. 3.3.0) using "pip install keras-tcn" on virtual env where tensorflow-gpu (ver. 2.3.0) was already installed.
I found that keras-tcn automatically installs the latest version of tensorflow (cpu version) ver. 2.4.1.
As a consequence, I have both tensorflow cpu (ver. 2.4.1) and gpu version (2.3.0), and due to their different version of package dependencies it causes compatibility issues.
Is there any way to install keras-tcn without installing tensorflow cpu version?

**Comment by philipperemy** [comment]
@kiminc66 try this:

https://stackoverflow.com/questions/12759761/python-pip-force-install-ignoring-dependencies

```
pip install keras-tcn --no-dependencies
```
