### ISSUE TITLE
'ValueError: Unknown layer: TCN' when trying to save the model using mode.save()

### ISSUE THREAD

**Issue by clearly-outsane** [philipperemy/keras-tcn#188]
**Describe the bug**
When I try to save my model which has a TCN layer from this library(this repo) it doesn't work

**Paste a snippet**
![image](https://user-images.githubusercontent.com/44093134/108750619-408d1080-7567-11eb-811f-3bb73454c901.png)

**Dependencies**
Just running it on colab with tensorflow version 2.4.x

**Comment by philipperemy** [comment]
@clearly-outsane try this:

```python
from tcn import TCN
from keras.initializers import glorot_uniform
my_model = keras.models.load_model("TCN_model", custom_objects={'TCN': TCN, 'GlorotUniform': glorot_uniform()})
```

Not sure if you need the `glorot_uniform` but I put it anyway. I haven't had time to see if it was necessary. The TCN layer is definitely necessary.

**Comment by philipperemy** [comment]
Let me know if it worked ;)

**Comment by clearly-outsane** [comment]
Oh thank you I'll try this. I apologise for not being too familiar with how to handle this so thanks!

**Comment by philipperemy** [comment]
No problem!

**Comment by clearly-outsane** [comment]
Yes it works!
