### ISSUE TITLE
How to exactly use keras-tcn for Many to Many regression?

### ISSUE THREAD

**Issue by zeydabadi** [philipperemy/keras-tcn#189]
Hi,
I have installed the tcn using `pip install keras-tcn`.
From the Readme file, I learned that the current version does not support many to many regression, and it is suggested a workaround for this. However, it is not clear to me how to apply this change and if there would a way to pass the number of time steps in the output features to the last `Dense()` layer?
For example, please consider this case that the input to the TCN model has the shape (batch_size, 24, 8), and the TCN output shape should have the shape (batch_size, 6, 2). Would it be possible to clear this case with an example code?

Thank you!

**Comment by philipperemy** [comment]
@zeydabadi. Try this:

```python
"""
#Trains a TCN on the IMDB sentiment classification task.
Output after 1 epochs on CPU: ~0.8611
Time per epoch on CPU (Core i7): ~64s.
Based on: https://github.com/keras-team/keras/blob/master/examples/imdb_bidirectional_lstm.py
"""
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import RepeatVector

from tcn import TCN

# many to many example.
# the input to the TCN model has the shape (batch_size, 24, 8),
# and the TCN output shape should have the shape (batch_size, 6, 2).

batch_size, timesteps, input_dim = 64, 24, 8
output_timesteps, output_dim = 6, 2

batch_x = np.random.uniform(size=(batch_size, timesteps, input_dim))
batch_y = np.random.uniform(size=(batch_size, output_timesteps, output_dim))

model = Sequential(
    layers=[
        TCN(input_shape=(timesteps, input_dim)),
        RepeatVector(output_timesteps),
        Dense(output_dim)
    ]
)

model.summary()
model.compile('adam', 'mse')

print('Train...')
model.fit(batch_x, batch_y, batch_size=batch_size)
```

**Comment by philipperemy** [comment]
Source: https://datascience.stackexchange.com/questions/46491/what-is-the-job-of-repeatvector-and-timedistributed
