### ISSUE TITLE
about the initial state like RNN, LSTM or GRU

### ISSUE THREAD

**Issue by cyber520** [philipperemy/keras-tcn#190]
Thanks for your nice work. But I am still confused about this question, like the API below,
tf.compat.v1.nn.dynamic_rnn(
    cell, inputs, sequence_length=None, **initial_state**=None, dtype=None,
    parallel_iterations=None, swap_memory=False, time_major=False, scope=None
)
In the traditional RNN, there's a variable called **initial state**, but **in the tcn, I could not see the value**. Could you please tell me how to solve this dilema, thanks for your reply!

**Comment by philipperemy** [comment]
Yes, an LSTM/GRU has an initial state because it contains hidden vectors and cells.
A TCN does not have states. Think about it as a CNN model that is able to work on time series.

**Comment by cyber520** [comment]
But I need this variable for training, do you have any ideas for solve this dilema, Thks for your reply.

**Comment by philipperemy** [comment]
You don't need to have it for TCN. If you have it somewhere just set it to None.
