### ISSUE TITLE
Testing time_series_forecasting.py with version 3.3.1, the prediction results are very different from version 3.2.1

### ISSUE THREAD

**Issue by HalfMAI** [philipperemy/keras-tcn#193]
**Describe the bug**
Testing time_series_forecasting.py with version 3.3.1, the prediction results are very different from version 3.2.1

**Paste a snippet**
3.3.1 notebook:
![image](https://user-images.githubusercontent.com/5293796/111455762-294dd700-8751-11eb-80b3-403eb607bf22.png)
https://colab.research.google.com/drive/1xTjddAcNgNRpXzRXZbkq3HzmwTxsBVJg?usp=sharing

3.2.1 notbook:
![image](https://user-images.githubusercontent.com/5293796/111455801-34a10280-8751-11eb-8b24-3549e25e03e7.png)
https://colab.research.google.com/drive/1lgmAD2Em6rjxrOMj6wkcpabxvWbCEX84?usp=sharing

**Dependencies**
tensorflow  == 2.4.1

**Comment by philipperemy** [comment]
@HalfMAI we changed some of the default parameters in 3.3.1. In your first plot, it seems that the training got stuck at the beginning and the optimizer could not work properly. If you re-run a few times do you always see this behavior?

**Comment by philipperemy** [comment]
Can you try the 3.3.1 with the previous set of hyper parameters here: https://github.com/philipperemy/keras-tcn/commit/d3e01fd5a95146871487a0065959d87027c18ea7 (the one in red on the left are the previous ones).

**Comment by HalfMAI** [comment]
> Can you try the 3.3.1 with the previous set of hyper parameters here: [d3e01fd](https://github.com/philipperemy/keras-tcn/commit/d3e01fd5a95146871487a0065959d87027c18ea7) (the one in red on the left are the previous ones).

Thanks for the reply. After resetting the default parameters as before, it did work after a few tests.
Here are the results after rebooting and testing several times.
![image](https://user-images.githubusercontent.com/5293796/111724017-73dd6980-889f-11eb-8444-ffac5874ac15.png)
![image](https://user-images.githubusercontent.com/5293796/111724086-95d6ec00-889f-11eb-97b1-27ae325b48a7.png)

**Comment by philipperemy** [comment]
@HalfMAI okay so might be worth reverting to the default parameters.
