### ISSUE TITLE
Why does the perceptive field formula differ from the calculation?

### ISSUE THREAD

**Issue by Alexander-Serov** [philipperemy/keras-tcn#196]
**Describe the bug**
The readme provides the following perception field calculation formula:
https://user-images.githubusercontent.com/12395799/106308730-6d4c5180-6261-11eb-82e9-a12a1958058d.png
![image](https://user-images.githubusercontent.com/22743277/111906436-e17cc780-8a50-11eb-84e8-69aec4afe15e.png)
where one sees `(k[n]-1)` under the sum.
However, the current code (v.3.3.1) uses `k[n]` in the expression ( https://github.com/philipperemy/keras-tcn/blob/455a035251d84840bfffbd761889615776b2c303/tcn/tcn.py#L248 ).
I was wondering if it's a bug or I am missing something?

After all, the difference is a factor of `k/(k-1)`, which does matter for applications. For `kernel_size = 3` (default), this is 1.5 times. 

Btw, there seems to be a square bracket out of place in the formula.

**Paste a snippet**
Irrelevant.

**Dependencies**
Irrelevant.

**Comment by philipperemy** [comment]
@Alexander-Serov yeah there's something wrong here. I'll try to investigate that more.

**Comment by philipperemy** [comment]
Seems like the correct formula is `1 + self.nb_stacks * sum([d * (self.kernel_size+1) for d in self.dilations])`.
From some of the tests I did.

**Comment by philipperemy** [comment]
![image](https://user-images.githubusercontent.com/4516927/112719486-9117d500-8f3c-11eb-9190-178e873a3773.png)

**Comment by philipperemy** [comment]
![image](https://user-images.githubusercontent.com/4516927/112719508-a55bd200-8f3c-11eb-83c0-88c6171a07d7.png)

Here is the right formula. I'm going to update the code and the README.

**Comment by philipperemy** [comment]
Thanks for raising this problem! It has been merged to master: https://github.com/philipperemy/keras-tcn/commit/bb92425485309042fff120d8ce264998e3562ed8.

A new version 3.4.0 was released.

**Comment by philipperemy** [comment]
I found this formula empirically by trying a lot of combinations of different parameters. I'm pretty sure it is correct when using the TCN. But theoretically, the 2 is not justified. It seems however the 2 present in the formula might be just a problem of notation (For example it's possible that if we want to specify dilations 1-2-4-8, we should only give to 1-2-4 to TensorFlow). One's should inspect the Conv1D code to see.

**Comment by philipperemy** [comment]
I added a note in the README. For later work.

**Comment by philipperemy** [comment]
Ref: https://stackoverflow.com/questions/63073760/using-dilated-convolution-in-keras
