### ISSUE TITLE
How to use TCN for multidimensional time series prediction？

### ISSUE THREAD

**Issue by dingfengqian** [philipperemy/keras-tcn#198]
Hi, Thanks very much for your open codes. I have a quenstion about the prediction for multidimensional data.
If the input for TCN is set (None, 10, 5), it means that a window contain 10 data, and the dimension of each data is 5. I want to know how the TCN to work for the prediction, is to create a TCN for each dimension to make a separate prediction?
Looking forward to your reply.

**Comment by Luux** [comment]
Hi, I'm not sure what you mean by that? For prediction, you also input a time series just like in training. The shapes are the same as with a normal LSTM.
So for (None, 10, 5) you have 10 time steps where each has 5 features. The _None_ is for the batch size, so you can ignore that and just look at the (10, 5).

**Comment by dingfengqian** [comment]
> 
> 
> Hi, I'm not sure what you mean by that? For prediction, you also input a time series just like in training. The shapes are the same as with a normal LSTM.
> So for (None, 10, 5) you have 10 time steps where each has 5 features. The _None_ is for the batch size/entry of the current sample within a minibatch, so you can ignore that and just look at the (10, 5). For prediction, it is the same; you just input the entire sequence.

Thanks for your reply. For the predction of (None, 10, 5), I want to know whether it can be regarded as a TCN model with the same parameters to make separate predictions for these 5 dimensions. That is, a TCN model that makes separate predictions for 5 inputs of (None, 10, 1).

**Comment by Luux** [comment]
So if you want to make separate predictions where the features should be treated as independent (-> should not influence/"know" each other entirely!) then you'd really have to create different TCN models.

If you do not want to treat them as completely independent features and just want 5 output dimensions as well, you can use one TCN normally.

**Comment by philipperemy** [comment]
@Luux thanks for helping and replying to Ding. I can add a few more things.
@dingfengqian Your input_dim dimension is similar to the channel of an RGB image and a simple convolution. So yes there will be some interactions. It is definitely not the case where we fetch one by one the input dimensions and run the TCN one each of them. Inside the filters, there are some matrices that will map input_dim to nb_filters (the ouput_dim of the convolution).

https://www.tensorflow.org/api_docs/python/tf/nn/conv2d

**Comment by Luux** [comment]
> IF YOU DO NOT WANT ANY INTERACTIONS: then, push the input_dim in the batch dimension, and run your TCN with input_dim=1. If you have (None, 10, 5), reshape it to (None * 5, 10, 1), call TCN on layer, obtain (None * 5, 1) [assuming it's a regression problem], and reshape it again to a list of 5 elements of shape (None, 1).

But only if the same filters/weights can be applied for each of these entries, of course. If they are features that depict entirely different things that cannot be modeled in the same way, you need different TCNs of course.

**Comment by philipperemy** [comment]
I'll close this issue for now as I think we gave ample information.
