### ISSUE TITLE
Dilation rate vs dilations argument

### ISSUE THREAD

**Issue by huvar** [philipperemy/keras-tcn#2]
Hi,

In your examples the dilations are dilatations=[1, 2, 4, 8]. This is in fact in-line with the imageof the example from WaveNet.
![WaveNet Example](https://raw.githubusercontent.com/philipperemy/keras-tcn/master/misc/Dilated_Conv.png) 
However this will lead to a dilation rate of 2**dilations, which implies the first dilation is 2 instead of 1. Is this a mistake? is there any reason why a dilation_depth parameter is not used instead?

**Comment by philipperemy** [comment]
The image does not reflect exactly the example in the code.

You are right here. You can just pass `dilatations=[0, 1, 2, 3, 4]` and you would fall back to just having a dilatation_depth equal to 5.

There's no reason why a `dilation_depth` is not used.
