### ISSUE TITLE
Receptive field description and examples

### ISSUE THREAD

**Issue by strokovnjaka** [philipperemy/keras-tcn#207]
My 5cents to the _"In theory, the 2 is not justified. We are still not sure why in practice we need to add this 2 in the formula."_ question, as stated in the [README](https://github.com/philipperemy/keras-tcn#receptive-field).

The *2* is there because there are two `Conv1d` layers in a single `ResidualBlock`. 

First, note that the cited [paper](https://arxiv.org/abs/1803.01271) states _"This gives us two ways to increase the receptive field of the TCN: choosing larger filter sizes k and increasing the dilation factor d, where the effective history of one such layer is (k − 1)d."_
In my opinion, that defines receptive field as "maximum number of steps back in time from current sample at time *T*, that a filter from (block, layer, stack, TCN) can hit", or something in that sense. 
The [README](https://github.com/philipperemy/keras-tcn#receptive-field) seems to define receptive field as "maximum number of samples that filters from (block, layer, stack, TCN) can hit", which is basically *effective history + 1*, so no big deal there.

So, a level *i* `ResidualBlock`'s effective history is *E<sub>h</sub> = 2⋅(k-1)⋅d<sub>i</sub>*, with *k* being kernel size, and *d<sub>i</sub>* being dilation for the `ResidualBlock` at level *i*.

Next, as `ResidualBlock`s are stacked in a stack, its *E<sub>h</sub> = Σ(2⋅(k-1)⋅d<sub>i</sub>) = 2⋅(k-1)⋅Σd<sub>i</sub>*.

Next, as *N* stacks are stacked, their *E<sub>h</sub> = N⋅2⋅(k-1)⋅Σd<sub>i</sub>*.

As receptive field seems to be effective history plus current sample at time *T*, the formula *R<sub>field</sub> = 1 + 2⋅(k-1)⋅N⋅Σd<sub>i</sub>* is correct.

As far as example figures go, they do not match the formula. For the first figure of single stack *16 != 31 = 1 + 2⋅(2-1)⋅1⋅(1+2+4+8)*, and so on for others. Example figures include single `Conv1d` per layer, so the correct formula would be *R<sub>field</sub> = 1 + (k-1)⋅N⋅Σd<sub>i</sub>* (without the notorious *2*).

Description for the formula states _"...where *N<sub>s</sub>* is the number of stacks, *N<sub>b</sub>* is the number of residual blocks per stack..."_, 
but formula references *N<sub>stacks</sub>*. So instead of *N<sub>s</sub>* use *N<sub>stacks</sub>*, and somehow state that the number of residual blocks is
the number of *d<sub>i</sub>* s in the formula (or, even better, replace the formula image)

To avoid confusion, stating the formula for the examples, as well as correcting formula's descriptions, would be great.
If, of course, the above is correct :)

**Comment by philipperemy** [comment]
@strokovnjaka thank you so much! I will update the README ;)

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/commit/d51c4ea0cb6538bb9c49261b64da0d1ee05a223b
