### ISSUE TITLE
copy_memory example issue

### ISSUE THREAD

**Issue by HighPerformance01** [philipperemy/keras-tcn#21]
Hi all,

I think there is an issue in copy_memory example

It is giving below error without any change to the code:

InvalidArgumentError: Incompatible shapes: [158976] vs. [256,621]

**Comment by philipperemy** [comment]
@HighPerformance01 good catch!

**Comment by philipperemy** [comment]
@HighPerformance01 yeah currently investigating!

**Comment by philipperemy** [comment]
I added a hotfix here:

https://github.com/philipperemy/keras-tcn/commit/ca58d37cd7a3b70b9152413fa5d04b993e58fdfd

You can just 

```
git pull origin master
```

and it will work.

I'll remove it later when it's packaged inside Keras.

**Comment by HighPerformance01** [comment]
thank you very much for the quick resolution

**Comment by philipperemy** [comment]
You are welcome! Happy I could help on that!
Also if the copy memory gets stuck at 0.9856 in accuracy, it's normal. It sometimes happens.
Just re-run the task a few times and you'll get a successful run. Or just wait a long time and the model will somehow find the optimum.
