### ISSUE TITLE
Question: Multivariate TCN

### ISSUE THREAD

**Issue by farzinaa** [philipperemy/keras-tcn#215]
Hi, 
I Have a question about the dependencies of the elements in an input sequence: Is there anyways to learn the relationship of such element? 
For example in the exchange task there are 8 currencies. My understanding is that removing half of these currencies would not effect the prediction of the other four. OR adding extra features is redundant and will not effect the outcome of the prediction. Is this correct? 
If so, is it possible for the model to learn from other currencies/features and how one would approach this? 
Many thanks

**Comment by loySoGxj** [comment]
What kind of problem (background) are you thinking about exactly?

**Comment by loySoGxj** [comment]
Looking at the above url, it looks like a mixture of non-causal TCN and TCN. What kind of problem (background) are you thinking about?
At least it doesn't seem to apply to time series.

**Comment by farzinaa** [comment]
I am trying to predict time series with multiple features. The data are pressure in each valve in a system where valves are connected through pipes and pressure in valve A is always grater than pressure in valve B and pressure in valve C is lower than in valves B. 
I use sequences of [A, B, C, ...]. However sometimes the predicted value of B is grater than value of A.

**Comment by farzinaa** [comment]
Thank you. It is all clear now.
