### ISSUE TITLE
Default value of kernel_size

### ISSUE THREAD

**Issue by SujanaC** [philipperemy/keras-tcn#220]
**Describe the bug**
It seems that TCN has a default kernel_size of 2 but the documentation indicates a value of 3. Could you please check this and fix the documentation?

**Paste a snippet**
from tcn import TCN, tcn_full_summary

time_steps = 10
input_dim = 2
tcn_layer = TCN(input_shape=(time_steps,input_dim), nb_filters=1, use_skip_connections=False)

tcn_layer.get_config()

**Dependencies**
I am running TF Keras 2.5.0 on a macbook pro with M1 chip.

**Comment by philipperemy** [comment]
Maybe update to the latest version?

```
{'name': 'tcn', 'trainable': True, 'batch_input_shape': (None, 10, 2), 'dtype': 'float32', 'nb_filters': 1, 'kernel_size': 3, 'nb_stacks': 1, 'dilations': (1, 2, 4, 8, 16, 32), 'padding': 'causal', 'use_skip_connections': False, 'dropout_rate': 0.0, 'return_sequences': False, 'activation': 'relu', 'use_batch_norm': False, 'use_layer_norm': False, 'use_weight_norm': False, 'kernel_initializer': 'he_normal'}
```

```
virtualenv venv
pip install keras-tcn
python test.py
```

Where `test.py` contains:
```python
from tcn import TCN

time_steps = 10
input_dim = 2
tcn_layer = TCN(input_shape=(time_steps, input_dim), nb_filters=1, use_skip_connections=False)

print(tcn_layer.get_config())

```
