### ISSUE TITLE
TCN for Time Series Image Classification

### ISSUE THREAD

**Issue by Vishu26** [philipperemy/keras-tcn#229]
I want to classify images where the features (channels) represent each time step. So, the input to TCN would have `input_shape=(None, timesteps, height, width)`. The idea here is to incorporate spatial and temporal information for classification at the same time.

Is there a possibility I can modify TCN to use it as a ConvLSTM2D layer?

**Comment by philipperemy** [comment]
@Vishu26 you can't do it with TCN unless if you reshape your input to `(None, timesteps, height * width)`. Which is perfectly fine in terms of performance.

There's an example that can do that. It's called MNIST pixel: https://github.com/philipperemy/keras-tcn/tree/master/tasks/mnist_pixel.

You can refer to the original paper in the README to learn about the task.

**Comment by Vishu26** [comment]
Thank you for the reply! I found a nice paper which implements what I need - https://arxiv.org/abs/1811.10166

**Comment by philipperemy** [comment]
Good to hear!
