### ISSUE TITLE
Can TCN be used in an autoencoder? 

### ISSUE THREAD

**Issue by Caisho** [philipperemy/keras-tcn#23]
Can this be used as a layer in an autoencoder by stacking the TCN layers? Or would you need to do UpSampling1D ?

**Comment by philipperemy** [comment]
TCN is a combination of layers and is not considered as a layer. For example you cannot do:
```
model = Sequential()
model.add(TCN())
```

This is not possible. But of course you can add it inside an autoencoder. Just build your graph like you would for any other model.

**Comment by Caisho** [comment]
Ok thanks!

**Comment by philipperemy** [comment]
@Caisho welcome!
