### ISSUE TITLE
setup.py requirements on mac os

### ISSUE THREAD

**Issue by gdupret** [philipperemy/keras-tcn#231]
At least for M1 machine:

```
from setuptools import setup

setup(
    name='keras-tcn',
    version='3.4.2',
    description='Keras TCN',
    author='Philippe Remy',
    license='MIT',
    long_description_content_type='text/markdown',
    long_description=open('README.md').read(),
    packages=['tcn'],
    install_requires=[
        'numpy', 'tensorflow-macos', 'tensorflow_addons'
    ]
)
```

instead of

```
    install_requires=[
        'numpy', 'tensorflow', 'tensorflow_addons'
    ]
```

**Comment by philipperemy** [comment]
@gdupret do you have examples of other repos? I'm not sure about the best way to do that.

**Comment by psomers3** [comment]
maybe simply just something like:
```python
import platform
tensorflow = 'tensorflow'
if platform.system() == "Darwin" and platform.processor() == 'arm':
    tensorflow = 'tensorflow-macos'

install_requires = ['numpy', tensorflow, 'tensorflow_addons']

```

**Comment by philipperemy** [comment]
@gdupret can you try to run this pip install and let me know if it works on your Mac M1?

```
pip install keras-tcn-macos==1.0
```
If it does not work, you might have to run some of those commands beforehand:

```
brew install hdf5@1.8 <----------------------- select the right version
export HDF5_DIR=/opt/homebrew/Cellar/hdf5@1.8/1.8.22_2 <----------------------- here the right path

export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
```

The two problematic packages are `grpcio` and `h5py`.

**Comment by gdupret** [comment]
I made a clean install on a virtual environment,`pip install keras-tcn-macos==1.0` and ran tasks/exchange_rate/demo.ipynb successfully. Thank you for the fix!

**Comment by philipperemy** [comment]
@gdupret okay then I'll push it to the main branch then!

**Comment by philipperemy** [comment]
The compatibility with MacOS was pushed in 3.4.3. Please install it that way:

```
pip install --no-binary keras-tcn keras-tcn
```

The wheel was made for Linux and not for the Mac M1. Using `--no-binary` forces `pip` to download the sources and compile it.
