### ISSUE TITLE
Keras installation error

### ISSUE THREAD

**Issue by Rasipuram** [philipperemy/keras-tcn#24]
I could install tcn using pip install keras-tcn successfully without any error.
But when I use it as
"from tcn import tcn" the following error gets generated.
File "/Users/sowmyar/anaconda/lib/python2.7/site-packages/tcn/tcn.py", line 95
    print(f'Updated dilations from {dilations} to {new_dilations} because of backwards compatibility.')
                                                                                                     ^
SyntaxError: invalid syntax

Can you help me with this issue?

**Comment by philipperemy** [comment]
@Rasipuram Sure use python3.6!

**Comment by philipperemy** [comment]
Can you please comment this line and tell me if it runs? I've never tested it for python2.7

**Comment by philipperemy** [comment]
I removed the debug line anyway.

**Comment by Rasipuram** [comment]
It works for python 3.x. Thank you.

Even if the line is commented, it does not work for python 2.6
Please let me if there is any possible solution for python 2.6.

**Comment by philipperemy** [comment]
Hum I'm not sure how difficult it would be. Python 2.x is going to be decommissioned soon anyway.

**Comment by Rasipuram** [comment]
Thank you.

**Comment by lingdoc** [comment]
You should probably be clearer on the landing page that this library works best in Python 3. When I tried to load a TCN in Keras using Python 2.7.15 it gave the following error:
```File "/usr/local/lib/python2.7/site-packages/tcn/__init__.py", line 1, in <module> \
    from tcn.tcn import TCN, compiled_tcn
  File "/usr/local/lib/python2.7/site-packages/tcn/tcn.py", line 225
    print(f'model.x = {input_layer.shape}')
                                         ^
SyntaxError: invalid syntax```

I then installed in Python 3 and re-ran, and it works fine.

**Comment by philipperemy** [comment]
@lingdoc yep thank you I'm going to do that!

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/commit/d6f5d8ec7c505637bd3ff43461f9e576826c9ccc

**Comment by nhirons** [comment]
Seem to be getting the same error in Python 3:
```
File "/usr/local/lib/python3.5/dist-packages/tcn/tcn.py", line 221
    print(f'model.x = {input_layer.shape}')
```

**Comment by nhirons** [comment]
Nevermind, I see the f-string was introduced in 3.6. I unfortunately am stuck with 3.5 for now so I can just modify the module as needed.

**Comment by philipperemy** [comment]
@nhirons I can push a release without the f string!

**Comment by philipperemy** [comment]
@nhirons I pushed a version without the f-strings.

```
pip install keras-tcn --upgrade # (2.7.1)
```

Enjoy!

**Comment by nhirons** [comment]
Wow, so speedy! Thank you very much. F-strings seem cool too though, I hadn't come across them before.

**Comment by philipperemy** [comment]
Yeah cool isn't it? :)
