### ISSUE TITLE
data shape of tcn layer

### ISSUE THREAD

**Issue by Alan29535** [philipperemy/keras-tcn#241]
I would like to ask what is the output data shape from TCN layers. Currently, I am trying to combine TCN and transformer together. However, I cannot pass the output data of TCN  to the transformer directly. 
I think it's because the output data shape of TCN is not the same as the input data shape for the transformer. 
So could anyone tell me how to check the output data shape of TCN, or please give some suggestions on how to combine TCN and transformer together?

**Comment by philipperemy** [comment]
@Alan29535 you should be able to swap the LSTM and TCN classes. 

- TCN Input shape: https://github.com/philipperemy/keras-tcn#input-shape
- TCN output shape: https://github.com/philipperemy/keras-tcn#output-shape
