### ISSUE TITLE
Visualization of internal structure of TCN block

### ISSUE THREAD

**Issue by hlmhlr** [philipperemy/keras-tcn#247]
Hi, 

I want to visualize the internal structure of TCN block along with the input/output dimensions of various sub-blocks but i am unable to do so. 

I have tried various approaches including `visualkeras`, `keras-visualizer`, `model.summary(),` and so on. They only show the input and output dimensions of TCN block along the overall input and output dimensions of the model. None of them visualize the internal structure of TCN block. 

I will really appreciate for any kind and prompt response. 

Thanks,

**Comment by philipperemy** [comment]
@hlmhlr you need to use tensorboard.
