### ISSUE TITLE
Question: Skip connections

### ISSUE THREAD

**Issue by ajoomye** [philipperemy/keras-tcn#254]
Hi, Thank you for the amazing repo. What does the skip connection do? If I want a simple TCN as shown in the examples with a kernel size of 2 and dilations [1, 2, 4, 8]. Do I have to set the skip connection as false? And if it is set to True, is there a separate connection between the input and output layer?

**Comment by philipperemy** [comment]
@ajoomye hi sorry for late reply. Skip connections allow a better gradient flow. Each output layer is connected to each other, sum and pass to the last layer to calculate the prediction. I'd say, set it to `True` always.

**Comment by ajoomye** [comment]
Dear @philipperemy , Thank you for the response.
