### ISSUE TITLE
Error in compiled_tcn 

### ISSUE THREAD

**Issue by Rasipuram** [philipperemy/keras-tcn#26]
Hi, 
The shape of my input data is x_train: (856,119,68), y_train: (856,1)
where 68 are the dimension of the feature vector. I define model like this 
 
model = tcn.compiled_tcn(num_feat=68,
                         num_classes=5,
                         nb_filters=48,
                         kernel_size=68,
                         dilations=[1, 2, 4], #[2 ** i for i in range(9)],
                         nb_stacks=2,
                         max_len=119, #train_x[0:1].shape[1],
                         activation='norm_relu',
                         use_skip_connections=True,
                         return_sequences=True)

When I run 
model.fit(train_x, train_y, validation_data=(test_x, test_y), epochs=100,
               batch_size=256)
I get this following error
"""Error when checking target: expected activation_59 to have 3 dimensions, but got array with shape (856, 1)"""
Please let me know if I have to change anything in the code?

**Comment by philipperemy** [comment]
@Rasipuram first do the examples in the repository work for you?

**Comment by philipperemy** [comment]
`num_classes=5,` should not be defined here. It seems to be a regression problem!

So please refer to the example here: https://github.com/philipperemy/keras-tcn/blob/master/tasks/adding_problem/main.py

**Comment by philipperemy** [comment]
```
    model = compiled_tcn(return_sequences=False,
                         num_feat=x_train.shape[2],
                         num_classes=0,
                         nb_filters=24,
                         kernel_size=8,
                         dilations=[2 ** i for i in range(9)],
                         nb_stacks=2,
                         max_len=x_train.shape[1],
                         activation='norm_relu',
                         use_skip_connections=True,
                         regression=True,
                         dropout_rate=0)
```
should be something like that.

`return_sequences=False` !

**Comment by philipperemy** [comment]
Let me know if you have any trouble.

**Comment by Rasipuram** [comment]
Thank you. It worked!
Would like to know how it works for a 5-class classification problem.
