### ISSUE TITLE
num_feat documentation out of date?

### ISSUE THREAD

**Issue by swilson314** [philipperemy/keras-tcn#29]
This comment in tcn.py doesn't seem to jive with the code:

num_feat: A tensor of shape (batch_size, timesteps, input_dim).

**Comment by philipperemy** [comment]
Thanks for pointing out! https://github.com/philipperemy/keras-tcn/blob/6d71e1946910748a4fb99ce53b29d312ddfb82b2/tcn/tcn.py#L196
