### ISSUE TITLE
Missing num_classes in regression example

### ISSUE THREAD

**Issue by thoppe** [philipperemy/keras-tcn#3]
Testing the regression example from the README,

```
model = tcn.dilated_tcn(output_slice_index='last',
                        num_feat=20,
                        nb_filters=24,
                        kernel_size=8,
                        dilatations=[1, 2, 4, 8],
                        nb_stacks=8,
                        max_len=100,
                        activation='norm_relu',
                        regression=True)
```

gives the error

```
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
TypeError: dilated_tcn() missing 1 required positional argument: 'num_classes'
```

**Comment by philipperemy** [comment]
Hum `num_classes` parameters is present: https://github.com/philipperemy/keras-tcn/blob/5a33fa7b199870b9ce4607f7ccf2e35e887813eb/tcn/tcn.py#L42

Maybe you should:

```
cd keras-tcn
git pull origin master
pip install . --upgrade # to force re installation
```

Let me know if error still persists.

Thanks

**Comment by thoppe** [comment]
Hi @philipperemy , it's still an issue (the latest version was already installed). Here is a full example:

```
from tcn import tcn

model = tcn.dilated_tcn(output_slice_index='last',
                        num_feat=20,
                        nb_filters=24,
                        kernel_size=8,
                        dilatations=[1, 2, 4, 8],
                        nb_stacks=8,
                        max_len=100,
                        activation='norm_relu',
                        regression=True)
```


```
> python demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    regression=True)
TypeError: dilated_tcn() missing 1 required positional argument: 'num_classes'

```

I think this is coming from the fact that if `regression=True`, you shouldn't expect a value for `num_classes` (and [looking at the code](https://github.com/philipperemy/keras-tcn/blob/master/tcn/tcn.py) that seems to be the case). However, `num_classes` is a positional argument, so you must specify a value. The example in the README could be fixed (without changing code) to:

```
model = tcn.dilated_tcn(output_slice_index='last',
                        num_feat=20,
                        num_classess=None,
                        nb_filters=24,
                        kernel_size=8,
                        dilatations=[1, 2, 4, 8],
                        nb_stacks=8,
                        max_len=100,
                        activation='norm_relu',
                        regression=True)
```

If you like, I'll issue a PR for this. I've also noticed that keras gives `UserWarnings` which I've fixed in my local copy. I can issue a PR for those too! :)

**Comment by philipperemy** [comment]
@thoppe thank you so much, very looking forward to your PR if you can issue one :)

**Comment by thoppe** [comment]
A PR has been issued.

**Comment by philipperemy** [comment]
@thoppe thank you very much! I'm just waiting for my GPUs to test it and I'll merge it :)

**Comment by philipperemy** [comment]
Merged thanks :)
