### ISSUE TITLE
Add language model in the examples folder

### ISSUE THREAD

**Issue by zm714981790** [philipperemy/keras-tcn#30]
I want to learn how to process text data using tf.keras and tcn

**Comment by philipperemy** [comment]
@zm714981790 well you can take an architecture with LSTM and just swap the LSTM layer with the TCN layer.

**Comment by zm714981790** [comment]
> @zm714981790 well you can take an architecture with LSTM and just swap the LSTM layer with the TCN layer.

I means char_cnn  in https://github.com/locuslab/TCN/tree/master/TCN, not use lstm to do language model.

**Comment by philipperemy** [comment]
@zm714981790 got it. I haven't implemented it but feel free to make a contribution by submitting a pull request :)

**Comment by philipperemy** [comment]
You can refer to this example. It shows how to use TCN on text:

https://github.com/philipperemy/keras-tcn/blob/master/tasks/imdb_tcn.py
