### ISSUE TITLE
Does this project support non-causal TCN ?

### ISSUE THREAD

**Issue by zhengwsh** [philipperemy/keras-tcn#31]
As mentioned in title.

**Comment by philipperemy** [comment]
Yes https://github.com/philipperemy/keras-tcn#non-causal-tcn

**Comment by twistedmove** [comment]
> Yes https://github.com/philipperemy/keras-tcn#non-causal-tcn

Hi sorry to bother you, but I didn't see how to change to non-caussal tcn in your codes.

**Comment by philipperemy** [comment]
Use padding = same or valid
Refer to keras padding convention.
By default padding = causal

**Comment by philipperemy** [comment]
And yes it was not clear I’m going to add a guideline

**Comment by philipperemy** [comment]
@twistedmove done
