### ISSUE TITLE
Clarify what's happening if dilations=None

### ISSUE THREAD

**Issue by Luux** [philipperemy/keras-tcn#34]
"dilations" is treated as an optional argument that defaults to "None": `tcn.TCN(nb_filters=64, kernel_size=2, nb_stacks=1, dilations=None, activation='norm_relu', padding='causal', use_skip_connections=True, dropout_rate=0.0, return_sequences=True, name='tcn')`

In the readme, it only states "List. A dilation list. Example is: [1, 2, 4, 8, 16, 32, 64]."
and in the `__call__` function of tcn.py it seams that it gets converted to [1, 2, 4, 8, 16, 32, 64] when it's set to None.

In this case, I think it it should either default to [1, 2, 4, 8, 16, 32] directly instead of None or it should at least be stated in the docs that it behaves so since it's quite confusing this way. Or did i miss something?

**Comment by philipperemy** [comment]
@Luux good catch. I'm going to update that.

**Comment by philipperemy** [comment]
There's a PR here: https://github.com/philipperemy/keras-tcn/pull/35
I'm testing it on GPUs. When it's ready, I'll merge it.

**Comment by philipperemy** [comment]
Done. Keras 2.3.5 has been released.
