### ISSUE TITLE
channel_normalization layer

### ISSUE THREAD

**Issue by chenwenchang** [philipperemy/keras-tcn#36]
It seems like that channel_normalization layer is different from the weight norm layer in the paper “An Empirical Evaluation of Generic Convolutional and Recurrent Networks for Sequence Modeling”.

**Comment by chenwenchang** [comment]
I don't know why

**Comment by philipperemy** [comment]
@chenwenchang can you make a Pull Request?

**Comment by philipperemy** [comment]
Thanks for reporting by the way

**Comment by philipperemy** [comment]
Just for info, I'm working on a PR to make the implementation identical to the paper: https://github.com/philipperemy/keras-tcn/pull/42

**Comment by philipperemy** [comment]
Weight norm is not available in Keras.

https://github.com/philipperemy/keras-tcn/commit/141ef1c1fdfc2384aec5b24caa2e9624d486d9ef
