### ISSUE TITLE
Multiple identical dilations lead to name error

### ISSUE THREAD

**Issue by sander314** [philipperemy/keras-tcn#39]
When using (e.g.)

`tcn = TCN(27,dilations=[1, 1, 1, 2, 4, 8, 16, 32],return_sequences=False)(in1) `

The code gives an error

"The name "tcn_d_causal_conv_1_tanh_s0" is used 3 times in the model. All layer names should be unique."
This is due to the block naming in 'residual_block' not including the layer number, but only the parameters.

**Comment by philipperemy** [comment]
@sander314 good catch! Going to fix that asap

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/pull/40
Will be merged soon.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/commit/0ae28a04af891cc01934125154f14a1a47445690

```
pip install keras-tcn --upgrade
```

**Comment by sander314** [comment]
Confirmed working, thanks for the quick fix!
