### ISSUE TITLE
TCN with spectrograms as input 

### ISSUE THREAD

**Issue by miccio-dk** [philipperemy/keras-tcn#49]
Hello everyone,

we'd like to try your TCN layers for speech enhancement task.
Our model is an autoencoder which takes ~270ms of spectrogram data (noisy speech)with dimensionality (F, T, C) where:
- F is the number of frequency bins: 256
- T is the number of stft() frames: 16
- C is the number of channels: 1, but could be more
The output has the same dimensionality of the input and is supposed to represent an enhanced version of the input speech (duh!).

It is in our understanding that we have to:
- permute the first two dimensions in order to use our T-dimension as timesteps
- flatten the remaining F and C dimensions to obtain the proper tensor shape

However, it is not clear how to obtain the original dimensionality after stacking one or more TCNs, as well as how to the layer in a way that reduces/expands the dimensionality of the data.

Could you shed some light on it and/or highlight any pitfall in our approach? 
Thanks in advance!

**Comment by philipperemy** [comment]
I've updated the documentation: https://github.com/philipperemy/keras-tcn/blob/master/README.md#output-shape

keras.LSTM and TCN should interchangeable. They follow the same logic and same input/output.

So if your code works for LSTM, it will work for TCN.

**Comment by miccio-dk** [comment]
Alright! that makes sense now, I was indeed a bit confused regarding the "task".
Thanks for the explanation!

**Comment by philipperemy** [comment]
Thanks!
