### ISSUE TITLE
Plans to support for TensorFlow 2.0?

### ISSUE THREAD

**Issue by jeffheaton** [philipperemy/keras-tcn#60]
Are there plans to support TensorFlow 2.0?  When I try to use keras-tnn with TF 2.0, I get this error.  Which is likely related to the eager execution model of TF 2.0.

`
Using TensorFlow backend.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7d9b599be077> in <module>
     19 i = Input(batch_shape=(batch_size, timesteps, input_dim))
     20 
---> 21 o = TCN(return_sequences=False)(i)  # The TCN layers are here.
     22 o = Dense(1)(o)
     23 

~/miniconda3/envs/tensorflow-2.0/lib/python3.6/site-packages/tcn/tcn.py in __call__(self, inputs)
    119         x = inputs
    120         # 1D FCN.
--> 121         x = Convolution1D(self.nb_filters, 1, padding=self.padding)(x)
    122         skip_connections = []
    123         for s in range(self.nb_stacks):

~/miniconda3/envs/tensorflow-2.0/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/miniconda3/envs/tensorflow-2.0/lib/python3.6/site-packages/keras/layers/convolutional.py in __init__(self, filters, kernel_size, strides, padding, data_format, dilation_rate, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
    357             kernel_constraint=kernel_constraint,
    358             bias_constraint=bias_constraint,
--> 359             **kwargs)
    360 
    361     def get_config(self):

~/miniconda3/envs/tensorflow-2.0/lib/python3.6/site-packages/keras/layers/convolutional.py in __init__(self, rank, filters, kernel_size, strides, padding, data_format, dilation_rate, activation, use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraint, bias_constraint, **kwargs)
    103                  bias_constraint=None,
    104                  **kwargs):
--> 105         super(_Conv, self).__init__(**kwargs)
    106         self.rank = rank
    107         self.filters = filters

~/miniconda3/envs/tensorflow-2.0/lib/python3.6/site-packages/keras/engine/base_layer.py in __init__(self, **kwargs)
    130         if not name:
    131             prefix = self.__class__.__name__
--> 132             name = _to_snake_case(prefix) + '_' + str(K.get_uid(prefix))
    133         self.name = name
    134 

~/miniconda3/envs/tensorflow-2.0/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in get_uid(prefix)
     72     """
     73     global _GRAPH_UID_DICTS
---> 74     graph = tf.get_default_graph()
     75     if graph not in _GRAPH_UID_DICTS:
     76         _GRAPH_UID_DICTS[graph] = defaultdict(int)

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
`

**Comment by philipperemy** [comment]
@jeffheaton thanks for reporting. I will start having a look at the end of the week and see what I can do.

**Comment by philipperemy** [comment]
I pushed the updates in a feat branch. You can install the version compatible with tf 2.0 like this:

```
pip install tensorflow==2.0.0-beta1
pip install git+https://github.com/philipperemy/keras-tcn@tf20
```

When tensorflow 2.0 becomes an official release, I will push the changes to master.

Let me know if it works for you!

**Comment by jeffheaton** [comment]
Thanks, that sounds good!

**Comment by philipperemy** [comment]
Awesome!
