### ISSUE TITLE
Weight Initialization

### ISSUE THREAD

**Issue by Luux** [philipperemy/keras-tcn#63]
The default weight initialization in Keras is Glorot Uniform. I've read that for Conv2D layers you should use the initialization algorithm from Kaiming He instead. I'm not sure if that applies to 1D Conv that are used in keras-tcn, but it may be nice to have the choice regardless.

**Comment by philipperemy** [comment]
@Luux definitely a legit request! And I agree about Kaiming He. I'm going to work on this.

**Comment by philipperemy** [comment]
https://github.com/philipperemy/keras-tcn/pull/65

**Comment by philipperemy** [comment]
@Luux can you tell me if you're happy with the pull request? https://github.com/philipperemy/keras-tcn/pull/65

**Comment by philipperemy** [comment]
```
pip install keras-tcn --upgrade
```
2.8.2
https://github.com/philipperemy/keras-tcn/commit/8fdfcd6eed3cf5d6e81423de3ffe7161300b2bb3
