### ISSUE TITLE
Failed to get convolution algorithm

### ISSUE THREAD

**Issue by Blinky0815** [philipperemy/keras-tcn#68]
**Problem:**
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1d_1/convolution}}]]

The problem may be because I have got two GPUs (RTX 2080). I ran into the issue with CUDA 10.0 and 10.1

**Fix:**
_Add the following lines to your main.py_
**The fix has been tested with the "adding problem"**

from keras.backend.tensorflow_backend import set_session
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
sess = tf.Session(config=config)

**Comment by philipperemy** [comment]
Try this:

https://github.com/tensorflow/tensorflow/issues/24828#issuecomment-464957482

**Comment by Blinky0815** [comment]
Thanks, 
This is pretty much exactly what I provided as a fix. And that works well.

**Comment by philipperemy** [comment]
@Blinky0815 awesome happy that it could work for you!
