### ISSUE TITLE
Saving and Loading Model

### ISSUE THREAD

**Issue by itsaugat** [philipperemy/keras-tcn#70]
Thanks for creating this easy to access library. I am using it for time series forecasting scenario based on the example given. After training the model, I saved it in h5 format using save method in Keras. However, when I try to load the model again using load_model() it gives an error saying 

**This version performs the same function as Dropout, however it drops entire 1D feature maps instead of individual elements. If adjacent frames within feature maps are strongly correlated (as is normally the case in early convolution layers) then regular dropout will not regularize the**

**IndexError: tuple index out of range**

After some google search, I figured it might be because of the Lambda layer used in the model. In this scenario, what is the best option to save and load the TCN model ?

**Comment by philipperemy** [comment]
Thanks!

Save model to h5 is usually buggy in Keras. I much prefer saving the weights by calling `set_weights()` and `get_weights()`. I provided an example on how to do it here: https://github.com/philipperemy/keras-tcn/blob/master/tasks/save_reload_model.py

It uses dropout and it worked. So it should solve your problem :)

**Comment by farzinaa** [comment]
> Thanks!
> 
> Save model to h5 is usually buggy in Keras. I much prefer saving the weights by calling `set_weights()` and `get_weights()`. I provided an example on how to do it here:
> 
> https://github.com/philipperemy/keras-tcn/blob/master/tasks/save_reload_model.py
> 
> It uses dropout and it worked. So it should solve your problem :)

Hi. The link is not working. Any chance you can share the correct link? Thanks.

**Comment by philipperemy** [comment]
@farzinaa https://github.com/philipperemy/keras-tcn/blob/master/tasks/save_reload_sequential_model.py

**Comment by farzinaa** [comment]
Thanks you.
