### ISSUE TITLE
Why use more stacks over more dilated layers?

### ISSUE THREAD

**Issue by adamconkey** [philipperemy/keras-tcn#71]
The receptive field is a product of number of stacks, the largest dilation value, and kernel size. Let us say we fix `kernel_size = 2` . I would like to understand the difference between two different ways of achieving the same receptive field, say a receptive field of 256:
1. Use `nb_stacks=1` stacks, and use dilations `[1, 2, 4, 8, 16, 32, 64, 128]`
2. Use `nb_stacks=2` stacks, and use dilations `[1, 2, 4, 8, 16, 32, 64]`

In general, what kind of tradeoff am I making in choosing to increase stacks versus increase dilations to get the receptive field I want, or are they equivalent?

**Comment by philipperemy** [comment]
@adamconkey quoting from the wavenet deepmind paper https://arxiv.org/pdf/1609.03499.pdf

![image](https://user-images.githubusercontent.com/4516927/64140525-a3ed2500-ce3f-11e9-80a7-8f898fcaee31.png)

**Comment by philipperemy** [comment]
Is it clear enough? To be honest, I guess you should try both and see the one that works the best. It's always difficult to give a solid answer on why one way is better than the other in deep learning.

**Comment by philipperemy** [comment]
I'll close the issue now. Still searchable :)
