### ISSUE TITLE
 is it possible to use is in a 2d way? for example, video prediction?

### ISSUE THREAD

**Issue by JialinYan96** [philipperemy/keras-tcn#72]

**Comment by philipperemy** [comment]
Not at the moment, it's only for 1D or multi 1D time series predictions (like sound waves).

If you want to predict on video, you have to use Convolutions 3D

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv3D

This could be a nice extension to the current version of the TCN.

**Comment by philipperemy** [comment]
More information here: http://francescopochetti.com/video-classification-in-keras-a-couple-of-approaches/
