### ISSUE TITLE
Question about number of filters

### ISSUE THREAD

**Issue by RifqiAW** [philipperemy/keras-tcn#77]
I'm trying to replicate the result of my previous project that used LSTM with units = 256. And on the home page of this repo it says that number of filters is like units in LSTM. And since I want the tcn to remember the whole sequence I set the receptive field about equals to the sequence length. But with number of filters 256 I ended up with a network that is way larger than the LSTM counterpart. So how do I calculate the appropriate number of filters?

**Comment by philipperemy** [comment]
Yes those networks have a totally different architecture. Try to reduce the number of filters and/or reduce the dilations to match the number of parameters of your LSTM. Keep in mind that LSTM usually fail to remember more than 50 steps. So if your sequence is 1000 steps, you can build a TCN that can remember the last ~100 steps. It -of course- depends on the type of your data. But that could be something you can consider. Hope it helps.

**Comment by philipperemy** [comment]
Yes I would say a non-causal TCN could be equivalent to a Bidirectional LSTM here.
