### ISSUE TITLE
Confusing about the input and output

### ISSUE THREAD

**Issue by zibozzb** [philipperemy/keras-tcn#79]
Hi Philippe Rémy,
Thank you for your great work!!
I am a beginner in deep learning.
I am working on object motion state prediction. In my problem, the input is the current state (3 by 1 vector), and the output is the predicted state (2 by 1 vector).  For example, I want to predict a toy car, the inputs will be the current speed v, current position s, and current force f; the outputs will be the speed v and the position s in the next time step. The first 1000 steps are used to train the model. And I want to use this trained model to predict the next state when given the current state. 
I am just wondering how to set the input and output in TCN. 
Thanks!

**Comment by philipperemy** [comment]
Hi,

Well you can always try something like this.

If you have 3000 time steps, you start at time 1000. The first 0:1000 steps go in your X and step 1000 go in your Y. And then you increment by 1. You are now at time 1001. The last 1000 (so from 1 to 1001 excluded) go to your X and the step 1001 go in your Y.

Then you're going to have two big matrices X and Y of the shape:

X.shape = (num_samples = 3000-1000 = 2000, 1000, 3)
Y.shape = (num_samples, 1, 2)

Then you can just run TCN+Dense(2) like you would use a simple LSTM.

You can check this script.

https://github.com/philipperemy/keras-tcn/blob/master/tasks/time_series_forecasting.py

It's just with one feature. In your case you will have 3.
