### ISSUE TITLE
Size of receptive field

### ISSUE THREAD

**Issue by alextheseal** [philipperemy/keras-tcn#8]
Hi Phillippe, thanks for doing this code, it is very helpful and works well.

I am doing time series prediction so can choose a sequence as long or as short as I want for the TCN to work with. What I am not clear on is how the kernel size, dilation values and number of stacks interact to determine the receptive field size.

For example, if I have a kernel size=8, dilation values of [1,2,4,8] and stacks=3, how long should my sequence be so that it fully covers the receptive field of the TCN? Can you clarify?

**Comment by philipperemy** [comment]
@alextheseal I really don't have much time working on that now :/ Could you find an answer?

**Comment by alextheseal** [comment]
I'll dig through the dilated convolution code in Keras and see if I can figure it out.

**Comment by philipperemy** [comment]
Thanks! I'll probably be able to help in one or two weeks. Been quite busy with other projects.

**Comment by philipperemy** [comment]
@alextheseal thanks for the visuals. I could finally work on the project again and I updated the code. In your case, with kernel size=8, dilation values of [1,2,4,8] and stacks=3, the receptive field will 8 * 8 * 3 = 192.
