### ISSUE TITLE
Unclear loop in residual block

### ISSUE THREAD

**Issue by davidxujiayang** [philipperemy/keras-tcn#85]
Hi, 

Sorry for bothering again. In your tcn.py residual block, there is a loop "for k in range(2):", I'm not sure about the purpose of it. Could you kindly explain? Thanks

**Comment by philipperemy** [comment]
@psomers3 I think that's a question for you :)

**Comment by psomers3** [comment]
It was done that way in the original code, so I just kept it. I assume it was there because the TCN paper uses 2 identical causal convolutions in the residual block, but maybe there was a thought that it would potentially be extended.

**Comment by philipperemy** [comment]
I'll close this question. @davidxujiayang tell us if it's not clear :)
