### ISSUE TITLE
Could you support Masking layer？

### ISSUE THREAD

**Issue by nervemonkey** [philipperemy/keras-tcn#89]
I am working on a signal labeling problem，but I think cutting signal and training randomly will lead the model working badly on new signals.So, could you support keras Masking layer?

**Comment by nervemonkey** [comment]
sorry，I found problems appear when I use model.add . If I use o = layer(i)... ,the probloms will disappear.

**Comment by nervemonkey** [comment]
I found the answer which is Con1d by keras lacking supports for Masking layer.For seq labeling, I can only put the masking layer before dense.

**Comment by philipperemy** [comment]
Thank you @MLtoPWELC. You are right Conv1D does not support masking in Keras.
