### ISSUE TITLE
Confused about nb_stacks

### ISSUE THREAD

**Issue by jc114** [philipperemy/keras-tcn#9]
I'm reading the code and I'm just a little confused about the below lines:    
for s in range(nb_stacks):
        for i in dilatations:
            x, skip_out = residual_block(x, s, i, activation, nb_filters, kernel_size)

What is the interpretation of this? In the paper, I had thought that each layer would have its own dilation rate, typically 2 ** i for the ith layer. What is happening here?

**Comment by alextheseal** [comment]
I'm a bit confused about it too, but my understanding is that you can stack up the TCN blocks, increasing the receptive field as you do. So for a single stack, if the kernel size was 2, the dilations were [1,2,4,8], you would get the situation in the image below:

<img width="1298" alt="screen shot 2018-06-25 at 11 59 10 am" src="https://user-images.githubusercontent.com/40159126/41830054-10e56fda-7871-11e8-8591-4fa46680c17f.png">

so a receptive field of 16.

If you specified 2 stacks my intuition is that you would get the situation below, that is, an increase in the receptive field to 32:

![stack2](https://user-images.githubusercontent.com/40159126/41830618-a8f82a8a-7874-11e8-9d4f-2ebb70a31465.jpg)

If you increased the number of stacks, the size of the receptive field would increase again, such as below:

![stack3](https://user-images.githubusercontent.com/40159126/41830628-ae6e73d4-7874-11e8-8ecd-cea37efa33f1.jpg)

Philip, can you please confirm whether my understanding is correct please.

**Comment by philipperemy** [comment]
@alextheseal I wrote that some times ago but it looks correct.

**Comment by alextheseal** [comment]
Thanks!

**Comment by philipperemy** [comment]
Yeah I updated the code to reflect this. It was a bit confusing sorry about that :)

**Comment by philipperemy** [comment]
I'll update it again to incorporate only one single parameter for the dilations: `N`
```
dilations = [2**i for i in range(N)]
```
So that when we specify N=4, it would mean [0, 1, 2, 4, 8]
